### ISSUE TITLE
Community Organization list or dropdown of categories with focus area and other searchable tags

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#14]
Wish list/desired feature, not a bug. This pairs with request for Community Organizations to be searchable by Focus area or audience.

**Comment by derekwmiller** [comment]
@veshengro69 the list of community organizations is already searchable by focus areas, etc. via the search bar
example - https://www.portlandmaps.com/bps/cedb/#/community/organizations/1/?search=workforce

What do we need to see here? Additional form-style inputs to go along with the search bar? That's doable, though we generally avoid to not clutter the UI.
