### ISSUE TITLE
Add a “back to projects list” button or link after you create a new project 

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#22]
Wish list/desired feature, not a bug.

**Comment by derekwmiller** [comment]
the 'back to project list' button exists on all views. it's in the navigation header at the top of the page labeled 'Projects'

![image](https://github.com/BPSTechServices/cedb-public/assets/2798800/8994db5e-d86f-4c04-9b95-d228665f8a8e)


after creating a project, the application takes you to the 'project view' of that project
that is pretty standard for CRUD (create / read / update / delete) operations, and will be useful once we start tagging on more elements to the project view
