### ISSUE TITLE
Events/calendar new designations: Committee meeting AND Council meeting

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#26]

**Comment by derekwmiller** [comment]
@veshengro69 what did we want to do here? How is this different from filtering the calendar by event type?

**Comment by derekwmiller** [comment]
does this resolve this issue?
![image](https://github.com/BPSTechServices/cedb-public/assets/2798800/4af35123-5c2e-4a1e-84fd-a9dd99ddffe8)
