### ISSUE TITLE
In Organizations "Communities served" dropdown, add: Aging populations 

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#32]

**Comment by derekwmiller** [comment]
I don't see "communities served", but added this to audiences.

@WingGrabowski  -- Please close the issue if that is correct, or let me know if not.

**Comment by WingGrabowski** [comment]
Correct, sorry for the confusion!

**Comment by derekwmiller** [comment]
@WingGrabowski no problem
