### ISSUE TITLE
Generate a spreadsheet of data from the CEDB

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#34]
This is within the context of avoiding duplicate work. The User Group discussed what I'm calling "Cross-platform work" - we will move to using the database for most things but might generate a spreadsheet to track a specific project, say calling contacts pulled from the database. For this we'd filter and select specific orgs including contact information, like roles, phone #s and emails.

**Comment by derekwmiller** [comment]
will await further instruction from @WingGrabowski

**Comment by WingGrabowski** [comment]
Going to skuttle this.
