### ISSUE TITLE
Delete "Organization Type" field from Org pages

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#40]
I think this was an option we took off of the Community Organization Editor but is still showing up on the Org profile

**Comment by derekwmiller** [comment]
@WingGrabowski you are correct
I think we might need to add it back, actually

**Comment by derekwmiller** [comment]
per @WingGrabowski let's add back and use the list of org-types already in the database to start

**Comment by WingGrabowski** [comment]
Looks like this was decided on, different from request but as we discussed.
