### ISSUE TITLE
Create contact in assign contact in Community orgs not workign

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#42]
![Screenshot 2024-02-27 153606](https://github.com/BPSTechServices/cedb-public/assets/52471238/23f8a822-38ee-4a50-8e74-58f1b7ee7811)

**Comment by derekwmiller** [comment]
I was able to confirm the behavior, but the behavior resolved without direct intervention. If it happens again, please reopen this ticket and add a comment... drop my name via @derekwmiller so that I'm notified.
