### ISSUE TITLE
Activity log in community org page sometimes greying out, not proceeding

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#44]

**Comment by derekwmiller** [comment]
any additional detail you can provide (screenshots of the page or the console ideally) would help

**Comment by derekwmiller** [comment]
> any additional detail you can provide (screenshots of the page or the console ideally) would help

@WingGrabowski

**Comment by derekwmiller** [comment]
No need for additional info. I see the behavior.

**Comment by WingGrabowski** [comment]
Thanks, was reported by user group member and I was waiting until I saw the behavior but you beat me to the glitch
