### ISSUE TITLE
Shows as blank page 

### ISSUE THREAD

**Issue by WingGrabowski** [BPSTechServices/cedb-public#46]
For some users, seems worse on Chrome. Someone noted that it worked on Edge (gross) though not Chrome.

**Comment by derekwmiller** [comment]
What shows as a blank page? The whole application?

---------------------------------------------
Derek Miller | he/him/his
Bureau of Planning and Sustainability | OMF - BTS Corporate GIS
 www.portland.gov/bps<http://www.portland.gov/bps>

The City of Portland is committed to providing meaningful access. For accommodations, modifications, translation, interpretation or other services, please contact 503-823-7700 or use City TTY 503-823-6868.

From: Wing ***@***.***>
Sent: Wednesday, April 17, 2024 11:24 AM
To: BPSTechServices/cedb-public ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BPSTechServices/cedb-public] Shows as blank page (Issue #46)


For some users, seems worse on Chrome. Someone noted that it worked on Edge (gross) though not Chrome.

**Comment by derekwmiller** [comment]
@WingGrabowski fixed.
